/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_psics_pnative_FileFPSICS */

#ifndef _Included_org_psics_pnative_FileFPSICS
#define _Included_org_psics_pnative_FileFPSICS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_psics_pnative_FileFPSICS
 * Method:    fpsics
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_psics_pnative_FileFPSICS_fpsics
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
